kind: ConfigMap
apiVersion: v1
metadata:
  name: nos1000jours-web-pro-configmap
data:
  NODE_ENV: "production"
  MATOMO_SITE_ID: "47"
  MATOMO_URL: "https://matomo.fabrique.social.gouv.fr/"
  NEXT_PUBLIC_API_URL: "backoffice-develop-dev-les1000jours.dev.fabrique.social.gouv.fr"
